# Generated by Django 3.1 on 2022-11-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20221127_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug_field',
            new_name='slug',
        ),
    ]
